# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    # needs: test
    name: Docker Build, Tag, Push

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/saveblue/saveblue-backend:latest

  Deploy-on-Production-Server:
    runs-on: ubuntu-latest
    needs: Build-and-Push-Docker-Image
    name: Deploy on Production Server

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          # if image pull unauthorized, add this repo to Manage Actions access (Organization->Packages->problematic package->Package settings->Manage Actions access->Add Repository)
          script: |
            cd ./projects/saveblue/production
            docker login ghcr.io -u ${{github.actor}} -p ${{secrets.GITHUB_TOKEN}}
            docker-compose pull
            docker-compose up -d saveblue-backend
